import {StyleSheet, ImageBackground} from 'react-native';
export default StyleSheet.create({
  container: {
    backgroundColor: '#faf2ce',
    flex: 1,
  },
  headerContainer: {
    height: 80,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: 20,
  },
  headerText: {
    fontSize: 24,
    color: '#dcb200',
    fontWeight: 'bold',
  },
  viewContainer: {
    position: 'absolute',
    right: 20,
    top: 20,
  },
  viewImage: {
    height: 25,
    width: 25,
  },
  backTextWhite: {
    color: '#FFF',
  },
  rowFront: {
    alignItems: 'center',
    backgroundColor: '#fff',
    justifyContent: 'center',
    height: 75,
    marginBottom: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    borderRadius: 10,
    padding: 8,
  },
  rowBack: {
    alignItems: 'center',
    backgroundColor: '#001D63',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
    borderRadius: 12,
  },
  backRightBtn: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    width: 75,
  },
  backLeftBtn: {
    alignItems: 'flex-start',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    width: 200,
    paddingLeft: 22,
  },
  backRightBtnLeft: {
    backgroundColor: '#001D63',
    right: 75,
  },
  backRightBtnRight: {
    backgroundColor: 'gold',
    right: 0,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  backLeftBtnleft: {
    backgroundColor: 'red',
    left: 0,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
  },
  trash: {
    height: 30,
    width: 30,
  },
  tick: {
    position: 'absolute',
    right: 25,
    height: 30,
    width: 30,
  },
  fapContainer: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    height: 70,
    width: 70,
    backgroundColor: 'gold',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    zIndex: 99,
    elevation: 1,
  },
  cardTitleContainer: {
    padding: 20,
  },
  cardTitle: {
    color: '#001D63',
    fontSize: 19,
    borderBottomWidth: 1,
    borderBottomColor: '#707070',
    paddingRight: 10,
    paddingLeft: 10,
    paddingBottom: 5,
    marginBottom: 15,
  },
  cardRowContainer: {
    alignSelf: 'flex-end',
    padding: 10,
  },
  row: {
    flexDirection: 'row',
    paddingRight: 20,
    paddingLeft: 20,
    justifyContent: 'flex-end',
  },
  rowTitleContainer: {
    margin: 10,
    justifyContent: 'center',
  },
  rowTitleText: {
    color: '#7E8998',
    fontWeight: 'bold',
    fontSize: 16,
    width: 100,
    textAlign: 'right',
  },
  rowDataContainer: {
    margin: 10,
    width: '70%',
    justifyContent: 'flex-start',
  },
  checked: {
    width: 30,
    height: 30,
    marginLeft: 20,
  },
  rowDataText: {
    color: '#14254D',
    borderBottomColor: 'gold',
    borderBottomWidth: 0.4,
    width: '100%',
  },

  cellLine: {
    borderRightWidth: 1,
    borderColor: '#70707058',
  },
  flatListContainer: {
    flex: 1,
    justifyContent: 'space-around',
  },
  flatListItemContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '47%',
    backgroundColor: 'white',
    height: 250,
    marginBottom: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    padding: 5,
  },
  flatListItemText: {
    fontSize: 18,
    color: '#56513b',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  flatListItemImage: {
    position: 'absolute',
    top: 10,
    right: 10,
    height: 30,
    width: 30,
  },
});
